# Generated by Django 3.2.5 on 2021-07-16 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('period_cycle_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodcylcemodel',
            name='last_period_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
